#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
path=$DIR'/coletas/'
mkdir -p $path
export path
sudo service seedd stop
sudo rm $path'zscore.txt' 2>/dev/null
fname="$( date +"%Y%m%dT%H%M%S" )"
number=1
read -e -p "Enter XOR (f1, f2 etc) or RAW (f0) mode [Default = f0]: " -i "f0" var1


while ( true ); do
	before=`date +%s%3N`
	sudo seedd --limit-max-xfer --no-qa -$var1 -b 256 | xxd -b -c256 | cut -f 2-257 -d ' ' | sed 's/[^1]//g' | awk -v num="$number," '{ print num, length }' >>$path$fname.txt
	awk -v num="$number," -F ', ' '{s+=$2;sum+=$2;a[NR]=$2} END {print num, (s/NR-1024)/((22.627417)/sqrt(NR))}' $path$fname.txt >> $path'zscore.txt' 2>/dev/null
	number=$(( ++number ))
	after=`date +%s%3N`
	DELAY=`echo "1-(($after-$before)/1000)" | bc -l`
	sleep $DELAY 2>/dev/null
done &
echo -e "\e[1;34mStarting plot.py\e[0m"
sleep 3
./plot &
read -p "Press [Enter] key to stop..."
echo -e "\e[1;36;5mAll done!\e[0m"
sudo ps -ef | awk '/zbbla/{print$2}' | xargs kill 2>/dev/null

